CREATE TABLE fornecedor (
  id bigint(20) PRIMARY KEY AUTO_INCREMENT,
  nome varchar(60) NOT NULL,
  fantasia varchar(60) NOT NULL,
  sigla varchar(7) NOT NULL,
  logradouro varchar(60),
  bairro varchar(30),
  complemento varchar(30),
  cep varchar(15),
  telefone varchar(15),
  celular varchar(15),
  email varchar(100),
  clifor boolean,
  documento1 varchar(20),
  documento2 varchar(30),
  tipo varchar(1),
  id_cidade bigint(20),
  dados_bancarios boolean,
  conta varchar(15),
  tipo_conta varchar(20),
  id_agencia bigint(20),
  dependente bigint(2),
  FOREIGN KEY (id_agencia) REFERENCES agencia (id),
  FOREIGN KEY (id_cidade) REFERENCES cidade (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8