CREATE TABLE permissao (
  id bigint(20) PRIMARY KEY AUTO_INCREMENT,
  nome varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE grupo (
  id bigint(20) PRIMARY KEY AUTO_INCREMENT,
  nome varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8