CREATE TABLE conta_pagar (
  id bigint(20) PRIMARY KEY AUTO_INCREMENT,
  historico varchar(200),
  data_emissao date,
  vencimento date,
  valor decimal(10,2),
  documento varchar(30),
  status varchar(15),
  nota_fiscal varchar(20),
  parcela bigint(20),
  total_parcela bigint(20),
  id_conta_secundaria bigint(20),
  id_empresa bigint(20),
  id_fornecedor bigint(20),
  id_pagamento bigint(20),
  recibo boolean DEFAULT NULL,
  tem_nota boolean DEFAULT NULL,
  FOREIGN KEY (id_conta_secundaria) REFERENCES plano_conta_secundaria (id),
  FOREIGN KEY (id_empresa) REFERENCES empresa (id),
  FOREIGN KEY (id_fornecedor) REFERENCES fornecedor (id),
  FOREIGN KEY (id_pagamento) REFERENCES pagamento (id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8