CREATE TABLE cooperado (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  nome varchar(60) NOT NULL,
  crm varchar(10) DEFAULT NULL,
  titulo_eleitor varchar(80) DEFAULT NULL,
  sessao_eleitor varchar(5) DEFAULT NULL,
  zona_eleitor varchar(5) DEFAULT NULL,
  data_eleitor date DEFAULT NULL,
  ctps varchar(30) DEFAULT NULL,
  serie_ctps varchar(10) DEFAULT NULL,
  data_ctps date DEFAULT NULL,
  pis varchar(30) DEFAULT NULL,
  banco_pis varchar(30) DEFAULT NULL,
  data_pis date DEFAULT NULL,
  cpf varchar(30) DEFAULT NULL,
  rg varchar(30) DEFAULT NULL,
  data_rg date DEFAULT NULL,
  habilitacao varchar(30) DEFAULT NULL,
  categoria_hab varchar(2) DEFAULT NULL,
  data_habilitacao date DEFAULT NULL,
  reservista varchar(30) DEFAULT NULL,
  regiao_reservista varchar(20) DEFAULT NULL,
  data_reservista date DEFAULT NULL,
  certidao varchar(30) DEFAULT NULL,
  data_certidao date DEFAULT NULL,
  tipo_certidao varchar(20) DEFAULT NULL,
  estado_civil varchar(20) DEFAULT NULL,
  pai varchar(60) DEFAULT NULL,
  mae varchar(60) DEFAULT NULL,
  cidade_natal varchar(30) DEFAULT NULL,
  nacionalidade varchar(30) DEFAULT NULL,
  logradouro varchar(60) DEFAULT NULL,
  bairro varchar(30) DEFAULT NULL,
  cep varchar(15) DEFAULT NULL,
  complemento varchar(20) DEFAULT NULL,
  telefone varchar(15) DEFAULT NULL,
  celular varchar(15) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  data_nascimento date DEFAULT NULL,
  ativo tinyint(1) DEFAULT NULL,
  anotacao varchar(200) DEFAULT NULL,
  sexo varchar(10) DEFAULT NULL,
  id_cidade bigint(20) NOT NULL,
  id_agencia bigint(20) DEFAULT NULL,
  conta varchar(45) DEFAULT NULL,
  tipo_conta varchar(45) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY id_cidade (id_cidade),
  KEY id_agencia (id_agencia),
  CONSTRAINT cooperado_ibfk_1 FOREIGN KEY (id_cidade) REFERENCES cidade (id),
  CONSTRAINT cooperado_ibfk_2 FOREIGN KEY (id_agencia) REFERENCES agencia (id)
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=utf8